name: Custom Step Name Workflow

# Run this workflow on every push to the main branch
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # This is the required step with your email as its name
      - name: 23f1002852@ds.study.iitm.ac.in
        run: echo "This step is named with the required email address."

      - name: Final Step
        run: echo "Workflow complete."
